name: ffvus
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py312h06a4308_0
  - python=3.12.0=h996f2a0_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - arch==7.2.0
      - certifi==2025.4.26
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - distro==1.9.0
      - docutils==0.21.2
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - marimo==0.13.6
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - narwhals==1.38.0
      - networkx==3.4.2
      - nodejs-bin==18.4.0a4
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.81.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - patsy==1.0.1
      - pillow==11.1.0
      - psutil==7.0.0
      - pycrdt==0.11.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pymdown-extensions==10.15
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - statsmodels==0.14.4
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tomlkit==0.13.2
      - torch==2.6.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.1
      - uvicorn==0.34.2
      - websockets==15.0.1
